<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\city;

class citySeeder extends Seeder{
    public function run(){
        city::create(['province_id' => '1','name' => 'KAB. ACEH BARAT']);
        city::create(['province_id' => '1','name' => 'KAB. ACEH BARAT DAYA']);
        city::create(['province_id' => '1','name' => 'KAB. ACEH BESAR']);
        city::create(['province_id' => '1','name' => 'KAB. ACEH JAYA']);
        city::create(['province_id' => '1','name' => 'KAB. ACEH SELATAN']);
        city::create(['province_id' => '1','name' => 'KAB. ACEH SINGKIL']);
        city::create(['province_id' => '1','name' => 'KAB. ACEH TAMIANG']);
        city::create(['province_id' => '1','name' => 'KAB. ACEH TENGAH']);
        city::create(['province_id' => '1','name' => 'KAB. ACEH TENGGARA']);
        city::create(['province_id' => '1','name' => 'KAB. ACEH TIMUR']);
        city::create(['province_id' => '1','name' => 'KAB. ACEH UTARA']);
        city::create(['province_id' => '1','name' => 'KAB. BENER MERIAH']);
        city::create(['province_id' => '1','name' => 'KAB. BIREUEN']);
        city::create(['province_id' => '1','name' => 'KAB. GAYO LUES']);
        city::create(['province_id' => '1','name' => 'KAB. NAGAN RAYA']);
        city::create(['province_id' => '1','name' => 'KAB. PIDIE']);
        city::create(['province_id' => '1','name' => 'KAB. PIDIE JAYA']);
        city::create(['province_id' => '1','name' => 'KAB. SIMEULUE']);
        city::create(['province_id' => '1','name' => 'KOTA BANDA ACEH']);
        city::create(['province_id' => '1','name' => 'KOTA LANGSA']);
        city::create(['province_id' => '1','name' => 'KOTA LHOKSEUMAWE']);
        city::create(['province_id' => '1','name' => 'KOTA SABANG']);
        city::create(['province_id' => '1','name' => 'KOTA SUBULUSSALAM']);
        city::create(['province_id' => '2','name' => 'KOTA MEDAN']);
        city::create(['province_id' => '2','name' => 'KAB. ASAHAN']);
        city::create(['province_id' => '2','name' => 'KAB. TAPANULI TENGAH']);
        city::create(['province_id' => '2','name' => 'KOTA SIBOLGA']);
        city::create(['province_id' => '2','name' => 'KAB. DAIRI']);
        city::create(['province_id' => '2','name' => 'KAB. DELI SERDANG']);
        city::create(['province_id' => '2','name' => 'KAB. TOBA SAMOSIR']);
        city::create(['province_id' => '2','name' => 'KOTA BINJAI']);
        city::create(['province_id' => '2','name' => 'KAB. NIAS']);
        city::create(['province_id' => '2','name' => 'KOTA PADANG SIDEMPUAN']);
        city::create(['province_id' => '2','name' => 'KAB. SIMALUNGUN']);
        city::create(['province_id' => '2','name' => 'KAB. KARO']);
        city::create(['province_id' => '2','name' => 'KAB. LANGKAT']);
        city::create(['province_id' => '2','name' => 'KAB. TAPANULI UTARA']);
        city::create(['province_id' => '2','name' => 'KOTA TEBING TINGGI']);
        city::create(['province_id' => '2','name' => 'KAB. PADANG LAWAS UTARA']);
        city::create(['province_id' => '2','name' => 'KAB. MANDAILING NATAL']);
        city::create(['province_id' => '2','name' => 'KAB. NIAS SELATAN']);
        city::create(['province_id' => '2','name' => 'KAB. PADANG LAWAS']);
        city::create(['province_id' => '2','name' => 'KAB. SAMOSIR']);
        city::create(['province_id' => '2','name' => 'KAB. SERDANG BEDAGAI']);
        city::create(['province_id' => '2','name' => 'KAB. TAPANULI SELATAN']);
        city::create(['province_id' => '2','name' => 'KOTA TANJUNG BALAI']);
        city::create(['province_id' => '2','name' => 'KAB. BATU BARA']);
        city::create(['province_id' => '2','name' => 'KOTA GUNUNGSITOLI']);
        city::create(['province_id' => '2','name' => 'KAB. HUMBANG HASUNDUTAN']);
        city::create(['province_id' => '2','name' => 'KAB. LABUHANBATU']);
        city::create(['province_id' => '2','name' => 'KAB. LABUHANBATU SELATAN']);
        city::create(['province_id' => '2','name' => 'KAB. LABUHANBATU UTARA']);
        city::create(['province_id' => '2','name' => 'KAB. NIAS BARAT']);
        city::create(['province_id' => '2','name' => 'KAB. NIAS UTARA']);
        city::create(['province_id' => '2','name' => 'KAB. PAKPAK BHARAT']);
        city::create(['province_id' => '2','name' => 'KOTA PEMATANG SIANTAR']);
        city::create(['province_id' => '3','name' => 'KOTA PADANG']);
        city::create(['province_id' => '3','name' => 'KAB. TANAH DATAR']);
        city::create(['province_id' => '3','name' => 'KAB. PASAMAN']);
        city::create(['province_id' => '3','name' => 'KAB. PESISIR SELATAN']);
        city::create(['province_id' => '3','name' => 'KAB. PADANG PARIAMAN']);
        city::create(['province_id' => '3','name' => 'KOTA PARIAMAN']);
        city::create(['province_id' => '3','name' => 'KOTA PAYAKUMBUH']);
        city::create(['province_id' => '3','name' => 'KOTA SOLOK']);
        city::create(['province_id' => '3','name' => 'KOTA PADANG PANJANG']);
        city::create(['province_id' => '3','name' => 'KAB. DHARMASRAYA']);
        city::create(['province_id' => '3','name' => 'KAB. LIMA PULUH KOTA']);
        city::create(['province_id' => '3','name' => 'KAB. KEPULAUAN MENTAWAI']);
        city::create(['province_id' => '3','name' => 'KAB. PASAMAN BARAT']);
        city::create(['province_id' => '3','name' => 'KAB. SOLOK']);
        city::create(['province_id' => '3','name' => 'KAB. SOLOK SELATAN']);
        city::create(['province_id' => '3','name' => 'KAB. SIJUNJUNG']);
        city::create(['province_id' => '3','name' => 'KAB. AGAM']);
        city::create(['province_id' => '3','name' => 'KOTA BUKITTINGGI']);
        city::create(['province_id' => '3','name' => 'KOTA SAWAH LUNTO']);
        city::create(['province_id' => '4','name' => 'KOTA PEKANBARU']);
        city::create(['province_id' => '4','name' => 'KOTA DUMAI']);
        city::create(['province_id' => '4','name' => 'KAB. KAMPAR']);
        city::create(['province_id' => '4','name' => 'KAB. BENGKALIS']);
        city::create(['province_id' => '4','name' => 'KAB. INDRAGIRI HULU']);
        city::create(['province_id' => '4','name' => 'KAB. INDRAGIRI HILIR']);
        city::create(['province_id' => '4','name' => 'KAB. ROKAN HILIR']);
        city::create(['province_id' => '4','name' => 'KAB. ROKAN HULU']);
        city::create(['province_id' => '4','name' => 'KAB. SIAK']);
        city::create(['province_id' => '4','name' => 'KAB. KEPULAUAN MERANTI']);
        city::create(['province_id' => '4','name' => 'KAB. KUANTAN SINGINGI']);
        city::create(['province_id' => '4','name' => 'KAB. PELALAWAN']);
        city::create(['province_id' => '5','name' => 'KOTA JAMBI']);
        city::create(['province_id' => '5','name' => 'KAB. TANJUNG JABUNG BARAT']);
        city::create(['province_id' => '5','name' => 'KAB. MERANGIN']);
        city::create(['province_id' => '5','name' => 'KAB. BATANG HARI']);
        city::create(['province_id' => '5','name' => 'KAB. BUNGO']);
        city::create(['province_id' => '5','name' => 'KAB. KERINCI']);
        city::create(['province_id' => '5','name' => 'KAB. MUARO JAMBI']);
        city::create(['province_id' => '5','name' => 'KAB. SAROLANGUN']);
        city::create(['province_id' => '5','name' => 'KAB. TANJUNG JABUNG TIMUR']);
        city::create(['province_id' => '5','name' => 'KAB. TEBO']);
        city::create(['province_id' => '5','name' => 'KOTA SUNGAIPENUH']);
        city::create(['province_id' => '6','name' => 'KOTA PALEMBANG']);
        city::create(['province_id' => '6','name' => 'KAB. MUSI RAWAS']);
        city::create(['province_id' => '6','name' => 'KAB. OGAN KOMERING ULU']);
        city::create(['province_id' => '6','name' => 'KAB. OGAN KOMERING ILIR']);
        city::create(['province_id' => '6','name' => 'KAB. LAHAT']);
        city::create(['province_id' => '6','name' => 'KAB. MUARA ENIM']);
        city::create(['province_id' => '6','name' => 'KOTA PAGAR ALAM']);
        city::create(['province_id' => '6','name' => 'KOTA PRABUMULIH']);
        city::create(['province_id' => '6','name' => 'KAB. MUSI BANYUASIN']);
        city::create(['province_id' => '6','name' => 'KAB. BANYUASIN']);
        city::create(['province_id' => '6','name' => 'KAB. EMPAT LAWANG']);
        city::create(['province_id' => '6','name' => 'KAB. OGAN ILIR']);
        city::create(['province_id' => '6','name' => 'KAB. OGAN KOMERING ULU TIMUR']);
        city::create(['province_id' => '6','name' => 'KAB. OGAN KOMERING ULU SELATAN']);
        city::create(['province_id' => '6','name' => 'KOTA LUBUK LINGGAU']);
        city::create(['province_id' => '6','name' => 'KAB. MUSI RAWAS UTARA']);
        city::create(['province_id' => '6','name' => 'KAB. PENUKAL ABAB LEMATANG ILIR']);
        city::create(['province_id' => '7','name' => 'KOTA BENGKULU']);
        city::create(['province_id' => '7','name' => 'KAB. BENGKULU UTARA']);
        city::create(['province_id' => '7','name' => 'KAB. REJANG LEBONG']);
        city::create(['province_id' => '7','name' => 'KAB. BENGKULU SELATAN']);
        city::create(['province_id' => '7','name' => 'KAB. KAUR']);
        city::create(['province_id' => '7','name' => 'KAB. KEPAHIANG']);
        city::create(['province_id' => '7','name' => 'KAB. LEBONG']);
        city::create(['province_id' => '7','name' => 'KAB. SELUMA']);
        city::create(['province_id' => '7','name' => 'KAB. BENGKULU TENGAH']);
        city::create(['province_id' => '7','name' => 'KAB. MUKO MUKO']);
        city::create(['province_id' => '8','name' => 'KOTA BANDAR LAMPUNG']);
        city::create(['province_id' => '8','name' => 'KAB. LAMPUNG SELATAN']);
        city::create(['province_id' => '8','name' => 'KAB. LAMPUNG UTARA']);
        city::create(['province_id' => '8','name' => 'KOTA METRO']);
        city::create(['province_id' => '8','name' => 'KAB. LAMPUNG BARAT']);
        city::create(['province_id' => '8','name' => 'KAB. LAMPUNG TENGAH']);
        city::create(['province_id' => '8','name' => 'KAB. LAMPUNG TIMUR']);
        city::create(['province_id' => '8','name' => 'KAB. WAY KANAN']);
        city::create(['province_id' => '8','name' => 'KAB. TULANG BAWANG']);
        city::create(['province_id' => '8','name' => 'KAB. TANGGAMUS']);
        city::create(['province_id' => '8','name' => 'KAB. PESAWARAN']);
        city::create(['province_id' => '8','name' => 'KAB. MESUJI']);
        city::create(['province_id' => '8','name' => 'KAB. PESISIR BARAT']);
        city::create(['province_id' => '8','name' => 'KAB. PRINGSEWU']);
        city::create(['province_id' => '8','name' => 'KAB. TULANG BAWANG BARAT']);
        city::create(['province_id' => '9','name' => 'KOTA PANGKAL PINANG']);
        city::create(['province_id' => '9','name' => 'KAB. BANGKA']);
        city::create(['province_id' => '9','name' => 'KAB. BANGKA BARAT']);
        city::create(['province_id' => '9','name' => 'KAB. BANGKA TENGAH']);
        city::create(['province_id' => '9','name' => 'KAB. BANGKA SELATAN']);
        city::create(['province_id' => '9','name' => 'KAB. BELITUNG']);
        city::create(['province_id' => '9','name' => 'KAB. BELITUNG TIMUR']);
        city::create(['province_id' => '10','name' => 'KOTA BATAM']);
        city::create(['province_id' => '10','name' => 'KAB. LINGGA']);
        city::create(['province_id' => '10','name' => 'KAB. NATUNA']);
        city::create(['province_id' => '10','name' => 'KAB. KARIMUN']);
        city::create(['province_id' => '10','name' => 'KOTA TANJUNG PINANG']);
        city::create(['province_id' => '10','name' => 'KAB. BINTAN']);
        city::create(['province_id' => '10','name' => 'KAB. KEPULAUAN ANAMBAS']);
        city::create(['province_id' => '11','name' => 'KOTA JAKARTA SELATAN']);
        city::create(['province_id' => '11','name' => 'KOTA JAKARTA UTARA']);
        city::create(['province_id' => '11','name' => 'KOTA JAKARTA PUSAT']);
        city::create(['province_id' => '11','name' => 'KOTA JAKARTA BARAT']);
        city::create(['province_id' => '11','name' => 'KOTA JAKARTA TIMUR']);
        city::create(['province_id' => '11','name' => 'KAB. KEPULAUAN SERIBU']);
        city::create(['province_id' => '12','name' => 'KOTA BANDUNG']);
        city::create(['province_id' => '12','name' => 'KAB. BANDUNG']);
        city::create(['province_id' => '12','name' => 'KOTA CIMAHI']);
        city::create(['province_id' => '12','name' => 'KAB. SUMEDANG']);
        city::create(['province_id' => '12','name' => 'KOTA TASIKMALAYA']);
        city::create(['province_id' => '12','name' => 'KOTA BANJAR']);
        city::create(['province_id' => '12','name' => 'KAB. CIAMIS']);
        city::create(['province_id' => '12','name' => 'KAB. TASIKMALAYA']);
        city::create(['province_id' => '12','name' => 'KAB. GARUT']);
        city::create(['province_id' => '12','name' => 'KAB. PURWAKARTA']);
        city::create(['province_id' => '12','name' => 'KAB. BANDUNG BARAT']);
        city::create(['province_id' => '12','name' => 'KAB. SUBANG']);
        city::create(['province_id' => '12','name' => 'KAB. CIANJUR']);
        city::create(['province_id' => '12','name' => 'KOTA BEKASI']);
        city::create(['province_id' => '12','name' => 'KAB. BEKASI']);
        city::create(['province_id' => '12','name' => 'KOTA BOGOR']);
        city::create(['province_id' => '12','name' => 'KAB. BOGOR']);
        city::create(['province_id' => '12','name' => 'KOTA CIREBON']);
        city::create(['province_id' => '12','name' => 'KAB. INDRAMAYU']);
        city::create(['province_id' => '12','name' => 'KAB. KUNINGAN']);
        city::create(['province_id' => '12','name' => 'KAB. MAJALENGKA']);
        city::create(['province_id' => '12','name' => 'KAB. CIREBON']);
        city::create(['province_id' => '12','name' => 'KOTA DEPOK']);
        city::create(['province_id' => '12','name' => 'KAB. KARAWANG']);
        city::create(['province_id' => '12','name' => 'KAB. SUKABUMI']);
        city::create(['province_id' => '12','name' => 'KOTA SUKABUMI']);
        city::create(['province_id' => '12','name' => 'KAB. PANGANDARAN']);
        city::create(['province_id' => '13','name' => 'KAB. CILACAP']);
        city::create(['province_id' => '13','name' => 'KOTA MAGELANG']);
        city::create(['province_id' => '13','name' => 'KAB. KEBUMEN']);
        city::create(['province_id' => '13','name' => 'KAB. WONOSOBO']);
        city::create(['province_id' => '13','name' => 'KAB. PURWOREJO']);
        city::create(['province_id' => '13','name' => 'KAB. TEMANGGUNG']);
        city::create(['province_id' => '13','name' => 'KAB. MAGELANG']);
        city::create(['province_id' => '13','name' => 'KOTA SURAKARTA']);
        city::create(['province_id' => '13','name' => 'KAB. BOYOLALI']);
        city::create(['province_id' => '13','name' => 'KAB. KLATEN']);
        city::create(['province_id' => '13','name' => 'KAB. SRAGEN']);
        city::create(['province_id' => '13','name' => 'KAB. SUKOHARJO']);
        city::create(['province_id' => '13','name' => 'KAB. WONOGIRI']);
        city::create(['province_id' => '13','name' => 'KOTA SEMARANG']);
        city::create(['province_id' => '13','name' => 'KAB. JEPARA']);
        city::create(['province_id' => '13','name' => 'KAB. KUDUS']);
        city::create(['province_id' => '13','name' => 'KOTA PEKALONGAN']);
        city::create(['province_id' => '13','name' => 'KAB. BANYUMAS']);
        city::create(['province_id' => '13','name' => 'KAB. BATANG']);
        city::create(['province_id' => '13','name' => 'KAB. BLORA']);
        city::create(['province_id' => '13','name' => 'KAB. BREBES']);
        city::create(['province_id' => '13','name' => 'KAB. DEMAK']);
        city::create(['province_id' => '13','name' => 'KAB. KENDAL']);
        city::create(['province_id' => '13','name' => 'KAB. PATI']);
        city::create(['province_id' => '13','name' => 'KAB. PEMALANG']);
        city::create(['province_id' => '13','name' => 'KAB. GROBOGAN']);
        city::create(['province_id' => '13','name' => 'KAB. REMBANG']);
        city::create(['province_id' => '13','name' => 'KOTA SALATIGA']);
        city::create(['province_id' => '13','name' => 'KAB. TEGAL']);
        city::create(['province_id' => '13','name' => 'KOTA TEGAL']);
        city::create(['province_id' => '13','name' => 'KAB. SEMARANG']);
        city::create(['province_id' => '13','name' => 'KAB. PURBALINGGA']);
        city::create(['province_id' => '13','name' => 'KAB. BANJARNEGARA']);
        city::create(['province_id' => '13','name' => 'KAB. PEKALONGAN']);
        city::create(['province_id' => '13','name' => 'KAB. KARANGANYAR']);
        city::create(['province_id' => '14','name' => 'KOTA CILEGON']);
        city::create(['province_id' => '14','name' => 'KAB. PANDEGLANG']);
        city::create(['province_id' => '14','name' => 'KAB. LEBAK']);
        city::create(['province_id' => '14','name' => 'KOTA SERANG']);
        city::create(['province_id' => '14','name' => 'KAB. SERANG']);
        city::create(['province_id' => '14','name' => 'KOTA TANGERANG']);
        city::create(['province_id' => '14','name' => 'KAB. TANGERANG']);
        city::create(['province_id' => '14','name' => 'KOTA TANGERANG SELATAN']);
        city::create(['province_id' => '15','name' => 'KAB. JEMBER']);
        city::create(['province_id' => '15','name' => 'KAB. BANYUWANGI']);
        city::create(['province_id' => '15','name' => 'KAB. BONDOWOSO']);
        city::create(['province_id' => '15','name' => 'KOTA KEDIRI']);
        city::create(['province_id' => '15','name' => 'KAB. KEDIRI']);
        city::create(['province_id' => '15','name' => 'KOTA MADIUN']);
        city::create(['province_id' => '15','name' => 'KAB. MADIUN']);
        city::create(['province_id' => '15','name' => 'KAB. MAGETAN']);
        city::create(['province_id' => '15','name' => 'KAB. NGAWI']);
        city::create(['province_id' => '15','name' => 'KAB. PACITAN']);
        city::create(['province_id' => '15','name' => 'KAB. PONOROGO']);
        city::create(['province_id' => '15','name' => 'KAB. MOJOKERTO']);
        city::create(['province_id' => '15','name' => 'KAB. SIDOARJO']);
        city::create(['province_id' => '15','name' => 'KOTA MOJOKERTO']);
        city::create(['province_id' => '15','name' => 'KOTA MALANG']);
        city::create(['province_id' => '15','name' => 'KAB. BLITAR']);
        city::create(['province_id' => '15','name' => 'KOTA BLITAR']);
        city::create(['province_id' => '15','name' => 'KOTA BATU']);
        city::create(['province_id' => '15','name' => 'KAB. MALANG']);
        city::create(['province_id' => '15','name' => 'KAB. PROBOLINGGO']);
        city::create(['province_id' => '15','name' => 'KOTA PROBOLINGGO']);
        city::create(['province_id' => '15','name' => 'KAB. LUMAJANG']);
        city::create(['province_id' => '15','name' => 'KAB. PASURUAN']);
        city::create(['province_id' => '15','name' => 'KOTA PASURUAN']);
        city::create(['province_id' => '15','name' => 'KAB. BOJONEGORO']);
        city::create(['province_id' => '15','name' => 'KOTA SURABAYA']);
        city::create(['province_id' => '15','name' => 'KAB. LAMONGAN']);
        city::create(['province_id' => '15','name' => 'KAB. BANGKALAN']);
        city::create(['province_id' => '15','name' => 'KAB. JOMBANG']);
        city::create(['province_id' => '15','name' => 'KAB. NGANJUK']);
        city::create(['province_id' => '15','name' => 'KAB. PAMEKASAN']);
        city::create(['province_id' => '15','name' => 'KAB. SAMPANG']);
        city::create(['province_id' => '15','name' => 'KAB. SUMENEP']);
        city::create(['province_id' => '15','name' => 'KAB. TUBAN']);
        city::create(['province_id' => '15','name' => 'KAB. TULUNGAGUNG']);
        city::create(['province_id' => '15','name' => 'KAB. TRENGGALEK']);
        city::create(['province_id' => '15','name' => 'KAB. GRESIK']);
        city::create(['province_id' => '15','name' => 'KAB. SITUBONDO']);
        city::create(['province_id' => '16','name' => 'KOTA YOGYAKARTA']);
        city::create(['province_id' => '16','name' => 'KAB. BANTUL']);
        city::create(['province_id' => '16','name' => 'KAB. SLEMAN']);
        city::create(['province_id' => '16','name' => 'KAB. KULON PROGO']);
        city::create(['province_id' => '16','name' => 'KAB. GUNUNG KIDUL']);
        city::create(['province_id' => '17','name' => 'KOTA DENPASAR']);
        city::create(['province_id' => '17','name' => 'KAB. KARANGASEM']);
        city::create(['province_id' => '17','name' => 'KAB. BANGLI']);
        city::create(['province_id' => '17','name' => 'KAB. GIANYAR']);
        city::create(['province_id' => '17','name' => 'KAB. JEMBRANA']);
        city::create(['province_id' => '17','name' => 'KAB. KLUNGKUNG']);
        city::create(['province_id' => '17','name' => 'KAB. BULELENG']);
        city::create(['province_id' => '17','name' => 'KAB. TABANAN']);
        city::create(['province_id' => '17','name' => 'KAB. BADUNG']);
        city::create(['province_id' => '18','name' => 'KOTA MATARAM']);
        city::create(['province_id' => '18','name' => 'KOTA BIMA']);
        city::create(['province_id' => '18','name' => 'KAB. DOMPU']);
        city::create(['province_id' => '18','name' => 'KAB. LOMBOK TENGAH']);
        city::create(['province_id' => '18','name' => 'KAB. LOMBOK TIMUR']);
        city::create(['province_id' => '18','name' => 'KAB. SUMBAWA']);
        city::create(['province_id' => '18','name' => 'KAB. LOMBOK BARAT']);
        city::create(['province_id' => '18','name' => 'KAB. SUMBAWA BARAT']);
        city::create(['province_id' => '18','name' => 'KAB. BIMA']);
        city::create(['province_id' => '18','name' => 'KAB. LOMBOK UTARA']);
        city::create(['province_id' => '19','name' => 'KOTA KUPANG']);
        city::create(['province_id' => '19','name' => 'KAB. SUMBA TENGAH']);
        city::create(['province_id' => '19','name' => 'KAB. BELU']);
        city::create(['province_id' => '19','name' => 'KAB. ALOR']);
        city::create(['province_id' => '19','name' => 'KAB. TIMOR TENGAH UTARA']);
        city::create(['province_id' => '19','name' => 'KAB. FLORES TIMUR']);
        city::create(['province_id' => '19','name' => 'KAB. SIKKA']);
        city::create(['province_id' => '19','name' => 'KAB. MANGGARAI']);
        city::create(['province_id' => '19','name' => 'KAB. TIMOR TENGAH SELATAN']);
        city::create(['province_id' => '19','name' => 'KAB. ENDE']);
        city::create(['province_id' => '19','name' => 'KAB. NGADA']);
        city::create(['province_id' => '19','name' => 'KAB. SUMBA TIMUR']);
        city::create(['province_id' => '19','name' => 'KAB. SUMBA BARAT']);
        city::create(['province_id' => '19','name' => 'KAB. MANGGARAI BARAT']);
        city::create(['province_id' => '19','name' => 'KAB. MANGGARAI TIMUR']);
        city::create(['province_id' => '19','name' => 'KAB. NAGEKEO']);
        city::create(['province_id' => '19','name' => 'KAB. ROTE NDAO']);
        city::create(['province_id' => '19','name' => 'KAB. SUMBA BARAT DAYA']);
        city::create(['province_id' => '19','name' => 'KAB. LEMBATA']);
        city::create(['province_id' => '19','name' => 'KAB. KUPANG']);
        city::create(['province_id' => '19','name' => 'KAB. MALAKA']);
        city::create(['province_id' => '19','name' => 'KAB. SABU RAIJUA']);
        city::create(['province_id' => '20','name' => 'KOTA PONTIANAK']);
        city::create(['province_id' => '20','name' => 'KAB. KETAPANG']);
        city::create(['province_id' => '20','name' => 'KAB. SANGGAU']);
        city::create(['province_id' => '20','name' => 'KOTA SINGKAWANG']);
        city::create(['province_id' => '20','name' => 'KAB. SINTANG']);
        city::create(['province_id' => '20','name' => 'KAB. KAPUAS HULU']);
        city::create(['province_id' => '20','name' => 'KAB. BENGKAYANG']);
        city::create(['province_id' => '20','name' => 'KAB. LANDAK']);
        city::create(['province_id' => '20','name' => 'KAB. MELAWI']);
        city::create(['province_id' => '20','name' => 'KAB. SAMBAS']);
        city::create(['province_id' => '20','name' => 'KAB. SEKADAU']);
        city::create(['province_id' => '20','name' => 'KAB. KUBU RAYA']);
        city::create(['province_id' => '20','name' => 'KAB. KAYONG UTARA']);
        city::create(['province_id' => '20','name' => 'KAB. MEMPAWAH']);
        city::create(['province_id' => '21','name' => 'KAB. BARITO UTARA']);
        city::create(['province_id' => '21','name' => 'KAB. BARITO TIMUR']);
        city::create(['province_id' => '21','name' => 'KAB. MURUNG RAYA']);
        city::create(['province_id' => '21','name' => 'KAB. BARITO SELATAN']);
        city::create(['province_id' => '21','name' => 'KAB. KATINGAN']);
        city::create(['province_id' => '21','name' => 'KAB. KAPUAS']);
        city::create(['province_id' => '21','name' => 'KAB. GUNUNG MAS']);
        city::create(['province_id' => '21','name' => 'KAB. SERUYAN']);
        city::create(['province_id' => '21','name' => 'KAB. KOTAWARINGIN BARAT']);
        city::create(['province_id' => '21','name' => 'KAB. KOTAWARINGIN TIMUR']);
        city::create(['province_id' => '21','name' => 'KAB. LAMANDAU']);
        city::create(['province_id' => '21','name' => 'KAB. PULANG PISAU']);
        city::create(['province_id' => '21','name' => 'KAB. SUKAMARA']);
        city::create(['province_id' => '21','name' => 'KOTA PALANGKA RAYA']);
        city::create(['province_id' => '22','name' => 'KOTA BANJARMASIN']);
        city::create(['province_id' => '22','name' => 'KAB. HULU SUNGAI TENGAH']);
        city::create(['province_id' => '22','name' => 'KAB. HULU SUNGAI SELATAN']);
        city::create(['province_id' => '22','name' => 'KAB. TABALONG']);
        city::create(['province_id' => '22','name' => 'KOTA BANJARBARU']);
        city::create(['province_id' => '22','name' => 'KAB. HULU SUNGAI UTARA']);
        city::create(['province_id' => '22','name' => 'KAB. BARITO KUALA']);
        city::create(['province_id' => '22','name' => 'KAB. BANJAR']);
        city::create(['province_id' => '22','name' => 'KAB. TANAH LAUT']);
        city::create(['province_id' => '22','name' => 'KAB. BALANGAN']);
        city::create(['province_id' => '22','name' => 'KAB. KOTABARU']);
        city::create(['province_id' => '22','name' => 'KAB. TANAH BUMBU']);
        city::create(['province_id' => '22','name' => 'KAB. TAPIN']);
        city::create(['province_id' => '23','name' => 'KOTA BALIKPAPAN']);
        city::create(['province_id' => '23','name' => 'KAB. KUTAI KARTANEGARA']);
        city::create(['province_id' => '23','name' => 'KAB. PASER']);
        city::create(['province_id' => '23','name' => 'KAB. BERAU']);
        city::create(['province_id' => '23','name' => 'KOTA BONTANG']);
        city::create(['province_id' => '23','name' => 'KAB. KUTAI TIMUR']);
        city::create(['province_id' => '23','name' => 'KOTA SAMARINDA']);
        city::create(['province_id' => '23','name' => 'KAB. KUTAI BARAT']);
        city::create(['province_id' => '23','name' => 'KAB. MAHAKAM ULU']);
        city::create(['province_id' => '23','name' => 'KAB. PENAJAM PASER UTARA']);
        city::create(['province_id' => '24','name' => 'KOTA TARAKAN']);
        city::create(['province_id' => '24','name' => 'KAB. BULUNGAN']);
        city::create(['province_id' => '24','name' => 'KAB. MALINAU']);
        city::create(['province_id' => '24','name' => 'KAB. NUNUKAN']);
        city::create(['province_id' => '24','name' => 'KAB. TANA TIDUNG']);
        city::create(['province_id' => '25','name' => 'KOTA MANADO']);
        city::create(['province_id' => '25','name' => 'KAB. BOLAANG MONGONDOW']);
        city::create(['province_id' => '25','name' => 'KAB. KEPULAUAN SANGIHE']);
        city::create(['province_id' => '25','name' => 'KAB. MINAHASA']);
        city::create(['province_id' => '25','name' => 'KOTA BITUNG']);
        city::create(['province_id' => '25','name' => 'KAB. BOLAANG MONGONDOW UTARA']);
        city::create(['province_id' => '25','name' => 'KAB. KEPULAUAN TALAUD']);
        city::create(['province_id' => '25','name' => 'KAB. MINAHASA UTARA']);
        city::create(['province_id' => '25','name' => 'KAB. MINAHASA SELATAN']);
        city::create(['province_id' => '25','name' => 'KAB. MINAHASA TENGGARA']);
        city::create(['province_id' => '25','name' => 'KOTA TOMOHON']);
        city::create(['province_id' => '25','name' => 'KAB. BOLAANG MONGONDOW SELATAN']);
        city::create(['province_id' => '25','name' => 'KAB. BOLAANG MONGONDOW TIMUR']);
        city::create(['province_id' => '25','name' => 'KAB. KEPULAUAN SIAU TAGULANDANG BIARO (SITARO)']);
        city::create(['province_id' => '25','name' => 'KOTA KOTAMOBAGU']);
        city::create(['province_id' => '26','name' => 'KOTA PALU']);
        city::create(['province_id' => '26','name' => 'KAB. BANGGAI']);
        city::create(['province_id' => '26','name' => 'KAB. POSO']);
        city::create(['province_id' => '26','name' => 'KAB. TOLI-TOLI']);
        city::create(['province_id' => '26','name' => 'KAB. BANGGAI KEPULAUAN']);
        city::create(['province_id' => '26','name' => 'KAB. BUOL']);
        city::create(['province_id' => '26','name' => 'KAB. DONGGALA']);
        city::create(['province_id' => '26','name' => 'KAB. MOROWALI']);
        city::create(['province_id' => '26','name' => 'KAB. PARIGI MOUTONG']);
        city::create(['province_id' => '26','name' => 'KAB. TOJO UNA-UNA']);
        city::create(['province_id' => '26','name' => 'KAB. BANGGAI LAUT']);
        city::create(['province_id' => '26','name' => 'KAB. MOROWALI UTARA']);
        city::create(['province_id' => '26','name' => 'KAB. SIGI']);
        city::create(['province_id' => '27','name' => 'KOTA MAKASSAR']);
        city::create(['province_id' => '27','name' => 'KAB. BANTAENG']);
        city::create(['province_id' => '27','name' => 'KAB. BARRU']);
        city::create(['province_id' => '27','name' => 'KAB. BULUKUMBA']);
        city::create(['province_id' => '27','name' => 'KAB. ENREKANG']);
        city::create(['province_id' => '27','name' => 'KAB. JENEPONTO']);
        city::create(['province_id' => '27','name' => 'KAB. TANA TORAJA']);
        city::create(['province_id' => '27','name' => 'KAB. MAROS']);
        city::create(['province_id' => '27','name' => 'KOTA PALOPO']);
        city::create(['province_id' => '27','name' => 'KAB. PINRANG']);
        city::create(['province_id' => '27','name' => 'KAB. WAJO']);
        city::create(['province_id' => '27','name' => 'KAB. SINJAI']);
        city::create(['province_id' => '27','name' => 'KAB. TAKALAR']);
        city::create(['province_id' => '27','name' => 'KAB. BONE']);
        city::create(['province_id' => '27','name' => 'KAB. SOPPENG']);
        city::create(['province_id' => '27','name' => 'KAB. PANGKAJENE KEPULAUAN']);
        city::create(['province_id' => '27','name' => 'KAB. LUWU UTARA']);
        city::create(['province_id' => '27','name' => 'KAB. LUWU TIMUR']);
        city::create(['province_id' => '27','name' => 'KAB. GOWA']);
        city::create(['province_id' => '27','name' => 'KAB. KEPULAUAN SELAYAR']);
        city::create(['province_id' => '27','name' => 'KAB. LUWU']);
        city::create(['province_id' => '27','name' => 'KOTA PAREPARE']);
        city::create(['province_id' => '27','name' => 'KAB. SIDENRENG RAPPANG']);
        city::create(['province_id' => '27','name' => 'KAB. TORAJA UTARA']);
        city::create(['province_id' => '28','name' => 'KOTA KENDARI']);
        city::create(['province_id' => '28','name' => 'KAB. KOLAKA']);
        city::create(['province_id' => '28','name' => 'KAB. MUNA']);
        city::create(['province_id' => '28','name' => 'KAB. KONAWE']);
        city::create(['province_id' => '28','name' => 'KAB. BOMBANA']);
        city::create(['province_id' => '28','name' => 'KAB. KOLAKA UTARA']);
        city::create(['province_id' => '28','name' => 'KAB. WAKATOBI']);
        city::create(['province_id' => '28','name' => 'KOTA BAU-BAU']);
        city::create(['province_id' => '28','name' => 'KAB. BUTON']);
        city::create(['province_id' => '28','name' => 'KAB. BUTON SELATAN']);
        city::create(['province_id' => '28','name' => 'KAB. BUTON TENGAH']);
        city::create(['province_id' => '28','name' => 'KAB. BUTON UTARA']);
        city::create(['province_id' => '28','name' => 'KAB. KOLAKA TIMUR']);
        city::create(['province_id' => '28','name' => 'KAB. KONAWE KEPULAUAN']);
        city::create(['province_id' => '28','name' => 'KAB. KONAWE SELATAN']);
        city::create(['province_id' => '28','name' => 'KAB. KONAWE UTARA']);
        city::create(['province_id' => '28','name' => 'KAB. MUNA BARAT']);
        city::create(['province_id' => '29','name' => 'KOTA GORONTALO']);
        city::create(['province_id' => '29','name' => 'KAB. GORONTALO']);
        city::create(['province_id' => '29','name' => 'KAB. BOALEMO']);
        city::create(['province_id' => '29','name' => 'KAB. GORONTALO UTARA']);
        city::create(['province_id' => '29','name' => 'KAB. POHUWATO']);
        city::create(['province_id' => '29','name' => 'KAB. BONE BOLANGO']);
        city::create(['province_id' => '30','name' => 'KAB. MAMUJU']);
        city::create(['province_id' => '30','name' => 'KAB. MAJENE']);
        city::create(['province_id' => '30','name' => 'KAB. POLEWALI MANDAR']);
        city::create(['province_id' => '30','name' => 'KAB. MAMASA']);
        city::create(['province_id' => '30','name' => 'KAB. MAMUJU UTARA']);
        city::create(['province_id' => '30','name' => 'KAB. MAMUJU TENGAH']);
        city::create(['province_id' => '31','name' => 'KOTA AMBON']);
        city::create(['province_id' => '31','name' => 'KAB. MALUKU TENGAH']);
        city::create(['province_id' => '31','name' => 'KAB. MALUKU TENGGARA']);
        city::create(['province_id' => '31','name' => 'KAB. BURU']);
        city::create(['province_id' => '31','name' => 'KAB. KEPULAUAN ARU']);
        city::create(['province_id' => '31','name' => 'KAB. SERAM BAGIAN BARAT']);
        city::create(['province_id' => '31','name' => 'KAB. SERAM BAGIAN TIMUR']);
        city::create(['province_id' => '31','name' => 'KAB. MALUKU TENGGARA BARAT']);
        city::create(['province_id' => '31','name' => 'KAB. BURU SELATAN']);
        city::create(['province_id' => '31','name' => 'KAB. MALUKU BARAT DAYA']);
        city::create(['province_id' => '31','name' => 'KOTA TUAL']);
        city::create(['province_id' => '32','name' => 'KOTA TERNATE']);
        city::create(['province_id' => '32','name' => 'KAB. HALMAHERA BARAT']);
        city::create(['province_id' => '32','name' => 'KAB. HALMAHERA SELATAN']);
        city::create(['province_id' => '32','name' => 'KAB. HALMAHERA TENGAH']);
        city::create(['province_id' => '32','name' => 'KAB. HALMAHERA TIMUR']);
        city::create(['province_id' => '32','name' => 'KAB. HALMAHERA UTARA']);
        city::create(['province_id' => '32','name' => 'KAB. KEPULAUAN SULA']);
        city::create(['province_id' => '32','name' => 'KAB. PULAU MOROTAI']);
        city::create(['province_id' => '32','name' => 'KAB. PULAU TALIABU']);
        city::create(['province_id' => '32','name' => 'KOTA TIDORE KEPULAUAN']);
        city::create(['province_id' => '33','name' => 'KOTA JAYAPURA']);
        city::create(['province_id' => '33','name' => 'KAB. JAYAPURA']);
        city::create(['province_id' => '33','name' => 'KAB. BIAK NUMFOR']);
        city::create(['province_id' => '33','name' => 'KAB. MERAUKE']);
        city::create(['province_id' => '33','name' => 'KAB. NABIRE']);
        city::create(['province_id' => '33','name' => 'KAB. DOGIYAI']);
        city::create(['province_id' => '33','name' => 'KAB. JAYAWIJAYA']);
        city::create(['province_id' => '33','name' => 'KAB. ASMAT']);
        city::create(['province_id' => '33','name' => 'KAB. BOVEN DIGOEL']);
        city::create(['province_id' => '33','name' => 'KAB. KEEROM']);
        city::create(['province_id' => '33','name' => 'KAB. MAPPI']);
        city::create(['province_id' => '33','name' => 'KAB. PANIAI']);
        city::create(['province_id' => '33','name' => 'KAB. DEIYAI']);
        city::create(['province_id' => '33','name' => 'KAB. PEGUNUNGAN BINTANG']);
        city::create(['province_id' => '33','name' => 'KAB. PUNCAK JAYA']);
        city::create(['province_id' => '33','name' => 'KAB. SARMI']);
        city::create(['province_id' => '33','name' => 'KAB. SUPIORI']);
        city::create(['province_id' => '33','name' => 'KAB. WAROPEN']);
        city::create(['province_id' => '33','name' => 'KAB. YAHUKIMO']);
        city::create(['province_id' => '33','name' => 'KAB. MAMBERAMO RAYA']);
        city::create(['province_id' => '33','name' => 'KAB. MIMIKA']);
        city::create(['province_id' => '33','name' => 'KAB. INTAN JAYA']);
        city::create(['province_id' => '33','name' => 'KAB. KEPULAUAN YAPEN']);
        city::create(['province_id' => '33','name' => 'KAB. LANNY JAYA']);
        city::create(['province_id' => '33','name' => 'KAB. MAMBERAMO TENGAH']);
        city::create(['province_id' => '33','name' => 'KAB. NDUGA']);
        city::create(['province_id' => '33','name' => 'KAB. PUNCAK']);
        city::create(['province_id' => '33','name' => 'KAB. TOLIKARA']);
        city::create(['province_id' => '33','name' => 'KAB. YALIMO']);
        city::create(['province_id' => '34','name' => 'KAB. SORONG']);
        city::create(['province_id' => '34','name' => 'KOTA SORONG']);
        city::create(['province_id' => '34','name' => 'KAB. KAIMANA']);
        city::create(['province_id' => '34','name' => 'KAB. RAJA AMPAT']);
        city::create(['province_id' => '34','name' => 'KAB. SORONG SELATAN']);
        city::create(['province_id' => '34','name' => 'KAB. TELUK BINTUNI']);
        city::create(['province_id' => '34','name' => 'KAB. TELUK WONDAMA']);
        city::create(['province_id' => '34','name' => 'KAB. MANOKWARI']);
        city::create(['province_id' => '34','name' => 'KAB. FAKFAK']);
        city::create(['province_id' => '34','name' => 'KAB. MANOKWARI SELATAN']);
        city::create(['province_id' => '34','name' => 'KAB. MAYBRAT']);
        city::create(['province_id' => '34','name' => 'KAB. PEGUNUNGAN ARFAK']);
        city::create(['province_id' => '34','name' => 'KAB. TAMBRAUW']);
       
    }
}
